### ISSUE TITLE
lidarPointClouds.mat has false content

### ISSUE THREAD

**Issue by benyovszky** [mathworks/udacity-self-driving-data-subset#1]
udacity-self-driving-data-subset/drive_segment_11_18_16/lidarPointClouds.mat does not include a pointcloud, but some ascii information.
Please upload the pointcloud.

**Comment by anandraja13** [comment]
It looks like you may have used the "Download Zip" to download the repository instead of cloning it. The lidarPointClouds.mat file is large, and hence was stored using Git LFS. 

However, GitHub's "Download Zip" button does not provide the option of downloading files stored using Git LFS. See [this issue](https://github.com/git-lfs/git-lfs/issues/903) for more information. I have also reported the issue to GitHub.

In order to download the file, you can use [this link](https://github.com/mathworks/udacity-self-driving-data-subset/blob/master/drive_segment_11_18_16/lidarPointClouds.mat?raw=true).

Alternately, in MATLAB, you can do the following:
`baseDownloadURL = 'https://github.com/mathworks/udacity-self-driving-data-subset/raw/master/drive_segment_11_18_16/';`

`options = weboptions('Timeout', Inf);`
`websave(<downloadFileName>, baseDownloadURL + "lidarPointClouds.mat", options);`
